# Generated by Django 5.2.6 on 2025-10-13 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('employee_email', models.EmailField(max_length=50, unique=True)),
                ('employee_phone', models.CharField(max_length=15, unique=True)),
                ('employee_address', models.TextField(blank=True, null=True)),
                ('employee_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_status', models.BooleanField(default=True)),
                ('department', models.CharField(blank=True, choices=[('Tech', 'Tech'), ('Digital Marketing', 'Digital Marketing'), ('Video Editor', 'Video Editor'), ('RM', 'RM'), ('Admin', 'Admin'), ('HR', 'HR'), ('Field Team', 'Field Team'), ('Video Grapher', 'Video Grapher')], max_length=50, null=True)),
                ('shift_timings', models.CharField(blank=True, choices=[('09:30 to 17:30', '09:30 to 17:30'), ('10:00 to 18:00', '10:00 to 18:00')], max_length=20, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_in_image', models.ImageField(blank=True, null=True, upload_to='checkin_images/')),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('check_out_image', models.ImageField(blank=True, null=True, upload_to='checkout_images/')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=30)),
                ('remarks', models.TextField(blank=True, choices=[('On Time', 'On Time'), ('Grace', 'Grace'), ('Late', 'Late'), ('Permission', 'Permission'), ('Half Day', 'Half Day')], default='On Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='dashboard.employee')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
