# Generated by Django 5.2.6 on 2025-10-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_attendance_check_in_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('Tech', 'Tech'), ('Digital Marketing', 'Digital Marketing'), ('Video Editor', 'Video Editor'), ('RM', 'RM'), ('Admin', 'Admin'), ('HR', 'HR'), ('Field Team', 'Field Team'), ('Video Grapher', 'Video Grapher'), ('Media', 'Media')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shift_timings',
            field=models.CharField(blank=True, choices=[('09:00 to 06:00', '09:00 to 06:00'), ('09:30 to 17:30', '09:30 to 17:30'), ('10:00 to 18:00', '10:00 to 18:00')], max_length=20, null=True),
        ),
    ]
