# Generated by Django 5.2.6 on 2025-10-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='shift_timings',
            field=models.CharField(blank=True, choices=[('09:00 to 18:00', '09:00 to 18:00'), ('09:30 to 17:30', '09:30 to 17:30'), ('10:00 to 18:00', '10:00 to 18:00')], max_length=20, null=True),
        ),
    ]
