# Generated by Django 5.2.6 on 2025-11-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_employee_shift_timings'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
